import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import QRCode from'qrcode';import'./styles.css';import{beginReveal}from'./firebase';import{configured,login,createRoom,joinRoom,submitSecret,watchRoom,hideReveal,savePlayers,type Room}from'./firebase';import{capture,parseRoom,remainingMs,roomCode,winner,type Player}from'./game';
const adjective=['Amber','Velvet','Silver','Golden','Neon','Quiet'];const noun=['Atlas','Comet','Falcon','Lotus','Orbit','Cedar'];const demoNames=['Maya','Sam','Jordan','Priya'];
function App(){const initial=parseRoom(location.pathname,location.search);const[screen,setScreen]=useState<'home'|'setup'|'join'|'game'>(initial?'join':'home');const[code,setCode]=useState(initial);const[name,setName]=useState(localStorage.empireName||'');const[category,setCategory]=useState('Famous people or fictional characters');const[duration,setDuration]=useState(30);const[secret,setSecret]=useState('');const[uid,setUid]=useState('');const[room,setRoom]=useState<Room|null>(null);const[error,setError]=useState('');const[qr,setQr]=useState('');const[now,setNow]=useState(Date.now());const[demo,setDemo]=useState(!configured);const isHost=room?.hostId===uid;
useEffect(()=>{if(configured)login().then(u=>setUid(u.uid)).catch(e=>setError(e.message));else{let id=localStorage.empireDemoUid||crypto.randomUUID();localStorage.empireDemoUid=id;setUid(id)}},[]);
useEffect(()=>{if(screen!=='game'||!code||demo)return;return watchRoom(code,r=>{setRoom(r);if(!r)setError('Room not found')})},[screen,code,demo]);
useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id)},[]);
useEffect(()=>{if(room?.phase==='reveal'&&room.reveal&&remainingMs(room.reveal.endsAt,now)===0&&isHost&&!demo)hideReveal(code,uid)},[now,room?.phase]);
useEffect(()=>{if(!code)return;const url=`${location.origin}${import.meta.env.BASE_URL}${code}`;QRCode.toDataURL(url,{margin:1,width:220,color:{dark:'#18120d',light:'#fffaf3'}}).then(setQr)},[code]);
function remember(){localStorage.empireName=name}
async function host(){if(!name.trim())return setError('Add your name');remember();const c=roomCode();setCode(c);history.replaceState({},'',`${import.meta.env.BASE_URL}${c}`);if(demo){const p=mk(uid,name);const extra=Object.fromEntries(demoNames.map((n,i)=>[`demo${i}`,{...mk(`demo${i}`,n),submitted:true}]));setRoom({hostId:uid,phase:'lobby',createdAt:Date.now(),settings:{category,revealSeconds:duration},players:{[uid]:p,...extra}});setScreen('game')}else{await createRoom(c,uid,name,category,duration);setScreen('game')}}
async function join(){if(!name.trim()||!code.trim())return setError('Add your name and room code');remember();const c=code.toUpperCase();setCode(c);history.replaceState({},'',`${import.meta.env.BASE_URL}${c}`);if(demo){setError('Live rooms connect after Firebase setup. Use Host game to preview the full flow.');return}else{await joinRoom(c,mk(uid,name));setScreen('game')}}
async function submit(){if(!secret.trim())return; if(demo){setRoom(r=>r?{...r,players:{...r.players,[uid]:{...r.players[uid],submitted:true}}}:r)}else await submitSecret(code,uid,secret.trim());setSecret('')}
async function start(){if(!room)return;if(demo){const words=[secret||`${adjective[0]} ${noun[0]}`,...Object.keys(room.players).filter(x=>x!==uid).map((_,i)=>`${adjective[i+1]} ${noun[i+1]}`)];setRoom({...room,phase:'reveal',reveal:{words,endsAt:Date.now()+duration*1000}})}else await beginReveal(code,uid)}
function endReveal(){if(!room)return;if(demo)setRoom({...room,phase:'playing',reveal:undefined});else hideReveal(code,uid)}
async function doCapture(a:string,b:string){if(!room)return;const players=capture(room.players,a,b);if(demo)setRoom({...room,players,phase:winner(players)?'finished':'playing'});else await savePlayers(code,uid,players)}
const share=`${location.origin}${import.meta.env.BASE_URL}${code}`;if(screen==='home')return <Page><section className="hero"><div className="crown">♜</div><p className="eyebrow">The social memory game</p><h1>Build your<br/><em>Empire.</em></h1><p className="lead">Choose a secret identity. Remember the list. Guess your friends. Rule the room.</p><div className="actions"><button onClick={()=>setScreen('setup')}>Host a game</button><button className="ghost" onClick={()=>setScreen('join')}>Join with code</button></div>{demo&&<p className="demo">Preview mode · realtime setup in progress</p>}</section></Page>;
if(screen==='setup')return <Page><Card title="Host a game" back={()=>setScreen('home')}><Field label="Your name" value={name} set={setName} placeholder="Param"/><Field label="Secret category" value={category} set={setCategory}/><label>Reveal time <b>{duration} seconds</b><input type="range" min="15" max="60" step="5" value={duration} onChange={e=>setDuration(+e.target.value)}/></label><button onClick={host}>Create room</button><Error text={error}/></Card></Page>;
if(screen==='join')return <Page><Card title="Join a room" back={()=>setScreen('home')}><Field label="Room code" value={code} set={v=>setCode(v.toUpperCase())} placeholder="ABC234"/><Field label="Your name" value={name} set={setName} placeholder="Your name"/><button onClick={join}>Join game</button><Error text={error}/></Card></Page>;
if(!room)return <Page><div className="loader">Joining {code}…</div><Error text={error}/></Page>;
if(room.phase==='reveal'&&room.reveal){const left=Math.ceil(remainingMs(room.reveal.endsAt,now)/1000);return <Page><section className="reveal"><div className="timer">{left}</div><p>Remember every identity</p><div className="word-grid">{room.reveal.words.map(w=><span key={w}>{w}</span>)}</div>{isHost&&<button className="ghost" onClick={endReveal}>Hide now</button>}</section></Page>}
if(room.phase==='playing'||room.phase==='finished')return <Page><Board room={room} host={isHost} capture={doCapture} code={code}/></Page>;
const players=Object.values(room.players||{});return <Page><section className="lobby"><div className="room-head"><div><p className="eyebrow">Room {code}</p><h2>Gather your<br/>empire.</h2></div>{qr&&<img src={qr}/>}</div><div className="share"><span>{share}</span><button className="mini" onClick={()=>navigator.clipboard.writeText(share)}>Copy link</button></div><div className="lobby-grid"><div><h3>Players <b>{players.length}</b></h3>{players.map(p=><div className="player" key={p.id}><i>{p.name[0]}</i><span>{p.name}{p.id===room.hostId&&<small> Host</small>}</span><em className={p.submitted?'ready':''}>{p.submitted?'Ready':'Choosing…'}</em></div>)}</div><div className="secret"><p>Your secret identity</p>{room.players[uid]?.submitted?<><div className="sealed">✓ Sealed</div><small>Only the host can see identity mappings.</small></>:<><input value={secret} onChange={e=>setSecret(e.target.value)} placeholder="e.g. Lightning McQueen"/><button onClick={submit}>Seal my identity</button></>}</div></div>{isHost&&<div className="hostbar"><span>{players.filter(p=>p.submitted).length}/{players.length} ready</span><button disabled={players.filter(p=>p.submitted).length<3} onClick={start}>Reveal the list</button></div>}</section></Page>}
const mk=(id:string,n:string):Player=>({id,name:n,submitted:false,leaderId:id,members:[],eliminated:false});
function Board({room,host,capture,code}:{room:Room;host:boolean;capture:(a:string,b:string)=>void;code:string}){const alive=Object.values(room.players).filter(p=>!p.eliminated),win=winner(room.players);const[a,setA]=useState(alive[0]?.id||''),[b,setB]=useState(alive[1]?.id||'');return <section className="board"><p className="eyebrow">Room {code} · Game on</p><h2>{win?`${win.name} rules the empire.`:'Who remembers who?'}</h2><p className="muted">Guess aloud. The host records a correct capture; the losing empire moves as one.</p><div className="empires">{alive.map(p=><article key={p.id}><i>{p.name[0]}</i><h3>{p.name}</h3><p>{p.members.length+1} in empire</p><div>{p.members.map(id=><span key={id}>{room.players[id]?.name}</span>)}</div></article>)}</div>{host&&!win&&<div className="capture"><select value={a} onChange={e=>setA(e.target.value)}>{alive.map(p=><option value={p.id}>{p.name}</option>)}</select><span>captured</span><select value={b} onChange={e=>setB(e.target.value)}>{alive.map(p=><option value={p.id}>{p.name}</option>)}</select><button onClick={()=>capture(a,b)}>Record</button></div>}</section>}
function Page({children}:{children:React.ReactNode}){return <main><header><a href={import.meta.env.BASE_URL}>EMPIRE</a><span>Remember. Guess. Conquer.</span></header>{children}<footer>Made for the room, not the screen.</footer></main>}
function Card({title,children,back}:{title:string;children:React.ReactNode;back:()=>void}){return <section className="card"><button className="back" onClick={back}>← Back</button><h2>{title}</h2>{children}</section>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <label>{label}<input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>};function Error({text}:{text:string}){return text?<p className="error">{text}</p>:null}createRoot(document.getElementById('root')!).render(<App/>);
