import {initializeApp} from 'firebase/app';import {getAuth,signInAnonymously} from 'firebase/auth';import {getDatabase,ref,set,onValue,update,get,remove,serverTimestamp} from 'firebase/database';import type {Player,Phase} from './game';
const config={apiKey:import.meta.env.VITE_FIREBASE_API_KEY,authDomain:import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,databaseURL:import.meta.env.VITE_FIREBASE_DATABASE_URL,projectId:import.meta.env.VITE_FIREBASE_PROJECT_ID,appId:import.meta.env.VITE_FIREBASE_APP_ID};export const configured=Boolean(config.apiKey&&config.databaseURL);const app=configured?initializeApp(config):null;export const auth=app?getAuth(app):null;export const db=app?getDatabase(app):null;
export type Room={hostId:string;phase:Phase;createdAt:number;settings:{revealSeconds:number;category:string};players:Record<string,Player>;reveal?:{words:string[];endsAt:number}};
export async function login(){if(!auth)throw new Error('Firebase is not configured');return(await signInAnonymously(auth)).user}export const roomRef=(code:string)=>ref(db!,`rooms/${code}`);
export function watchRoom(code:string,cb:(r:Room|null)=>void){let current:Room|null=null;let reveal:{words:string[];endsAt:number}|null=null;const emit=()=>cb(current?{...current,...(reveal?{reveal}:{})}:null);const offRoom=onValue(roomRef(code),s=>{current=s.val();emit()});const offReveal=onValue(ref(db!,`reveals/${code}`),s=>{reveal=s.val();emit()},()=>{reveal=null;emit()});return()=>{offRoom();offReveal()}}
export async function createRoom(code:string,hostId:string,hostName:string,category:string,revealSeconds:number){const player:Player={id:hostId,name:hostName,submitted:false,leaderId:hostId,members:[],eliminated:false};await update(ref(db!),{[`rooms/${code}/hostId`]:hostId,[`rooms/${code}/phase`]:'lobby',[`rooms/${code}/createdAt`]:Date.now(),[`rooms/${code}/settings`]:{category,revealSeconds},[`rooms/${code}/players/${hostId}`]:player})}
export async function joinRoom(code:string,p:Player){await set(ref(db!,`rooms/${code}/players/${p.id}`),p)}
export async function submitSecret(code:string,uid:string,word:string){await set(ref(db!,`submissions/${code}/${uid}`),{word,submittedAt:serverTimestamp()});await update(ref(db!,`rooms/${code}/players/${uid}`),{submitted:true})}
export async function beginReveal(code:string,hostId:string){const room=(await get(roomRef(code))).val() as Room;if(room.hostId!==hostId)throw new Error('Only the host can start');const submissions=(await get(ref(db!,`submissions/${code}`))).val() as Record<string,{word:string}>;const words=Object.values(submissions||{}).map(s=>s.word);if(words.length<3)throw new Error('At least 3 players must submit');const endsAt=Date.now()+room.settings.revealSeconds*1000;await set(ref(db!,`reveals/${code}`),{words:words.sort(()=>Math.random()-.5),endsAt});await set(ref(db!,`rooms/${code}/phase`),'reveal')}
export async function hideReveal(code:string,hostId:string){const snap=await get(roomRef(code));if(snap.val()?.hostId!==hostId)return;await set(ref(db!,`rooms/${code}/phase`),'playing');await remove(ref(db!,`reveals/${code}`))}
export async function savePlayers(code:string,hostId:string,players:Record<string,Player>){const snap=await get(roomRef(code));if(snap.val()?.hostId!==hostId)throw new Error('Only the host can update the board');await set(ref(db!,`rooms/${code}/players`),players)}
